server:
  port: 8080
  servlet:
    context-path: # 컨텍스트 경로 사용하지 않음

spring:
  application:
    name: habit-challenge
  
  # MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/habit_challenge?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: song010629
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # 이메일 설정 (개발용 Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: bruno010629@gmail.com  # 실제 Gmail 주소로 변경 필요
    password: urmpfymnezfkuehh  # Gmail 앱 비밀번호로 변경 필요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: ${kakao.redirect-uri}
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT 설정
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production
  expiration: 86400000  # 24시간 (밀리초)
  token-prefix: "Bearer "
  header: "Authorization"

# 카카오 OAuth2 설정
kakao:
  client-id: 0a0e82ecc56b0d606c7a40f7c8e75ddc # 카카오 개발자 콘솔에서 받은 REST API 키
  client-secret: bjZlrcjnZv5Kn6QxT56rFcpbWXFEnOfC  # 카카오 개발자 콘솔에서 받은 Client Secret
  redirect-uri: http://localhost:3000/kakao-callback  # 프론트엔드 리다이렉트 URI

# 로깅 설정
logging:
  level:
    com.habitchallenge.backend: DEBUG
    org.springframework.security: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.habitchallenge: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.OncePerRequestFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    path: logs/
    max-history: 7
    max-size: 10MB
